version: "3"

services:
  fastapi:
    build: .
    container_name: fastapi
    ports:
      - "8000:8000"
    networks:
      - my_network
    depends_on:
      - tika-server

  tika-server:
    image: apache/tika
    container_name: tika-server
    ports:
      - "9998:9998"
    networks:
      - my_network

networks:
  my_network: